#include <gtk/gtk.h>
#include "../include/GtkFramework/GtkFramework.h"
static void activate(GtkApplication *app, gpointer data){
GtkWidget *window = create_window(app, GTK_WINDOW_TOPLEVEL, "Default title", 5000, 5000, TRUE, GTK_WIN_POS_CENTER, TRUE, NULL, 1.0, FALSE);
GtkWidget *Header_bar = create_header_bar("UIBuilder", "Build your UI Application", NULL, TRUE);
add_header_bar_to_window(window, Header_bar);
GtkWidget *main_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *app_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *main_paned = create_paned(GTK_ORIENTATION_HORIZONTAL, 240, TRUE);
GtkWidget *hierarchy_widgets_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *hierarchy_widgets_label_box = create_box(GTK_ORIENTATION_HORIZONTAL, GTK_ALIGN_START, 0);
GtkWidget *hierarchy_widgets_label = create_label("Widgets Hierarchy", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_RIGHT, FALSE, 0, 0, TRUE);
add_to_box(hierarchy_widgets_label_box, hierarchy_widgets_label, START, TRUE, FALSE, 0, 0, 0, 0, 7);
add_to_box(hierarchy_widgets_box, hierarchy_widgets_label_box, START, FALSE, FALSE, 0, 7, 0, 12, 7);
GtkWidget *hierarchy_widgets_box_content = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *test_button = create_button(GTK_RELIEF_NORMAL, "This space is reserved for\n the Widgets Hierarchy", FALSE, NULL, NULL, NULL);
add_to_box(hierarchy_widgets_box_content, test_button, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(hierarchy_widgets_box, hierarchy_widgets_box_content, START, TRUE, TRUE, 0, 7, 0, 0, 7);
add_to_paned(main_paned, hierarchy_widgets_box, FIRST);
GtkWidget *build_space_paned = create_paned(GTK_ORIENTATION_HORIZONTAL, 710, TRUE);
GtkWidget *first_space_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *contents_space_paned = create_paned(GTK_ORIENTATION_VERTICAL, 500, TRUE);
GtkWidget *working_space_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *working_space_label_box = create_box(GTK_ORIENTATION_HORIZONTAL, GTK_ALIGN_START, 0);
GtkWidget *working_space_label = create_label("Working Space", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_RIGHT, FALSE, 0, 0, TRUE);
add_to_box(working_space_label_box, working_space_label, START, TRUE, FALSE, 0, 0, 0, 0, 7);
add_to_box(working_space_box, working_space_label_box, START, FALSE, FALSE, 0, 0, 0, 12, 7);
GtkWidget *working_space_box_content = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *working_space_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *test_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
add_to_frame(working_space_frame, test_box, 5, 5, 5, 5);
add_to_box(working_space_box_content, working_space_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(working_space_box, working_space_box_content, START, TRUE, TRUE, 0, 7, 7, 0, 0);
add_to_paned(contents_space_paned, working_space_box, FIRST);
GtkWidget *widgets_informations_space = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *widgets_informations_label_box = create_box(GTK_ORIENTATION_HORIZONTAL, GTK_ALIGN_START, 0);
GtkWidget *widgets_informations_label = create_label("Widgets Informations", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_RIGHT, FALSE, 0, 0, TRUE);
add_to_box(widgets_informations_label_box, widgets_informations_label, START, TRUE, FALSE, 0, 0, 0, 0, 7);
add_to_box(widgets_informations_space, widgets_informations_label_box, START, FALSE, FALSE, 0, 7, 0, 12, 7);
GtkWidget *widgets_informations_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *button_test4 = create_button(GTK_RELIEF_NORMAL, "This space is reserved for the Widgets Informations", FALSE, NULL, NULL, NULL);
add_to_box(widgets_informations_box, button_test4, START, TRUE, TRUE, 0, 7, 0, 0, 0);
add_to_box(widgets_informations_space, widgets_informations_box, START, TRUE, TRUE, 0, 7, 0, 0, 0);
add_to_paned(contents_space_paned, widgets_informations_space, SECOND);
add_to_box(first_space_box, contents_space_paned, START, TRUE, TRUE, 0, 7, 0, 7, 7);
add_to_paned(build_space_paned, first_space_box, FIRST);
GtkWidget *second_space_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *second_space_label_box = create_box(GTK_ORIENTATION_HORIZONTAL, GTK_ALIGN_START, 0);
GtkWidget *second_space_label = create_label("Widgets Catalog", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_RIGHT, FALSE, 0, 0, TRUE);
add_to_box(second_space_label_box, second_space_label, START, TRUE, FALSE, 0, 0, 0, 0, 7);
add_to_box(second_space_box, second_space_label_box, START, FALSE, FALSE, 0, 7, 0, 12, 7);
GtkWidget *widgets_catalog_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *switcher_catalog = create_switcher(2, TRUE);
add_to_box(widgets_catalog_box, switcher_catalog, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *stack_catalog = create_stack(switcher_catalog, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT, 500);
GtkWidget *scrolled_window_window = create_scrolled_window(FALSE, TRUE);
GtkWidget *Windows_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 7);
GtkWidget *window_case = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *window_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *window_label = create_label("Window", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_RIGHT, FALSE, 0, 0, TRUE);
add_to_frame(window_label_frame, window_label, 5, 5, 0, 0);
add_to_box(window_case, window_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *window_informations_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *window_informations_main_box = create_box(GTK_ORIENTATION_HORIZONTAL, -1, 0);
GtkWidget *window_informations_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *window_informations_app_label = create_label("Window", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_app_label, 0, 0, 1, 1);
GtkWidget *window_informations_app_value = create_entry("app", "Chose App for TOPLEVEL", TRUE, TRUE, 20, 0.5);
add_to_grid(window_informations_grid, window_informations_app_value, 0, 1, 1, 1);
GtkWidget *window_informations_type_label = create_label("Type", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_type_label, 1, 0, 1, 1);
GtkWidget *window_informations_type_value = create_entry("GTK_WINDOW_TOPLEVEL", "Chose Type of the window", TRUE, TRUE, 20, 0.5);
add_to_grid(window_informations_grid, window_informations_type_value, 1, 1, 1, 1);
GtkWidget *window_informations_title_label = create_label("Title", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_title_label, 2, 0, 1, 1);
GtkWidget *window_informations_title_value = create_entry("title", "Chose Title for TOPLEVEL", TRUE, TRUE, 20, 0.5);
add_to_grid(window_informations_grid, window_informations_title_value, 2, 1, 1, 1);
GtkWidget *window_informations_width_label = create_label("Width", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_width_label, 3, 0, 1, 1);
GtkWidget *window_informations_width_value = create_spin_button(0, 1000, 10, 800, 0, FALSE, TRUE);
add_to_grid(window_informations_grid, window_informations_width_value, 3, 1, 1, 1);
GtkWidget *window_informations_height_label = create_label("Height", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_height_label, 4, 0, 1, 1);
GtkWidget *window_informations_height_value = create_spin_button(0, 1000, 10, 600, 0, FALSE, TRUE);
add_to_grid(window_informations_grid, window_informations_height_value, 4, 1, 1, 1);
GtkWidget *window_informations_resizable_label = create_label("Resizable", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_resizable_label, 5, 0, 1, 1);
GtkWidget *window_informations_resizable_value = create_combo_box();
add_to_combo_box(window_informations_resizable_value, "TRUE");
add_to_combo_box(window_informations_resizable_value, "FALSE");
add_to_grid(window_informations_grid, window_informations_resizable_value, 5, 1, 1, 1);
GtkWidget *window_informations_position_label = create_label("Position", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_position_label, 6, 0, 1, 1);
GtkWidget *window_informations_position_value = create_combo_box();
add_to_combo_box(window_informations_position_value, "GTK_WIN_POS_CENTER");
add_to_combo_box(window_informations_position_value, "GTK_WIN_POS_CENTER_ON_PARENT");
add_to_combo_box(window_informations_position_value, "GTK_WIN_POS_MOUSE");
add_to_grid(window_informations_grid, window_informations_position_value, 6, 1, 1, 1);
GtkWidget *window_informations_decorate_label = create_label("Decorate", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_decorate_label, 7, 0, 1, 1);
GtkWidget *window_informations_decorate_value = create_combo_box();
add_to_combo_box(window_informations_decorate_value, "TRUE");
add_to_combo_box(window_informations_decorate_value, "FALSE");
add_to_grid(window_informations_grid, window_informations_decorate_value, 7, 1, 1, 1);
GtkWidget *window_informations_icon_label = create_label("Icon", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_icon_label, 8, 0, 1, 1);
GtkWidget *window_informations_icon_value = create_entry(NULL, "icon path", TRUE, TRUE, 20, 0.5);
add_to_grid(window_informations_grid, window_informations_icon_value, 8, 1, 1, 1);
GtkWidget *window_informations_opacity_label = create_label("Opacity", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_opacity_label, 9, 0, 1, 1);
GtkWidget *window_informations_opacity_value = create_spin_button(0, 1, 0.1, 1, 1, FALSE, TRUE);
add_to_grid(window_informations_grid, window_informations_opacity_value, 9, 1, 1, 1);
GtkWidget *window_informations_fullscreen_label = create_label("Fullscreen", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(window_informations_grid, window_informations_fullscreen_label, 10, 0, 1, 1);
GtkWidget *window_informations_fullscreen_value = create_combo_box();
add_to_combo_box(window_informations_fullscreen_value, "TRUE");
add_to_combo_box(window_informations_fullscreen_value, "FALSE");
add_to_grid(window_informations_grid, window_informations_fullscreen_value, 10, 1, 1, 1);
GtkWidget *window_informations_add_button = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(window_informations_grid, window_informations_add_button, 11, 0, 2, 1);
add_to_box(window_informations_main_box, window_informations_grid, START, TRUE, FALSE, 0, 21, 21, 0, 0);
add_to_frame(window_informations_frame, window_informations_main_box, 0, 0, 0, 0);
add_to_box(window_case, window_informations_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(Windows_box, window_case, START, TRUE, TRUE, 0, 7, 0, 0, 0);
GtkWidget *Header_bar_case = create_box(GTK_ORIENTATION_VERTICAL, GTK_ALIGN_START, 0);
GtkWidget *header_bar_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *header_bar_label = create_label("Header Bar", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(header_bar_label_frame, header_bar_label, 5, 5, 0, 0);
add_to_box(Header_bar_case, header_bar_label_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
GtkWidget *header_bar_informations_main_box_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *header_bar_informations_main_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *header_bar_informations_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *header_bar_informations_title_label = create_label("Title", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(header_bar_informations_grid, header_bar_informations_title_label, 0, 0, 1, 1);
GtkWidget *header_bar_informations_title_value = create_entry(NULL, "title", TRUE, TRUE, 20, 0.5);
add_to_grid(header_bar_informations_grid, header_bar_informations_title_value, 0, 1, 1, 1);
GtkWidget *header_bar_informations_subtitle_label = create_label("Subtitle", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(header_bar_informations_grid, header_bar_informations_subtitle_label, 1, 0, 1, 1);
GtkWidget *header_bar_informations_subtitle_value = create_entry(NULL, "subtitle", TRUE, TRUE, 20, 0.5);
add_to_grid(header_bar_informations_grid, header_bar_informations_subtitle_value, 1, 1, 1, 1);
GtkWidget *header_bar_informations_icon_label = create_label("Icon", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(header_bar_informations_grid, header_bar_informations_icon_label, 2, 0, 1, 1);
GtkWidget *header_bar_informations_icon_value = create_entry(NULL, "icon path", TRUE, TRUE, 20, 0.5);
add_to_grid(header_bar_informations_grid, header_bar_informations_icon_value, 2, 1, 1, 1);
GtkWidget *header_bar_informations_settings_label = create_label("Settings", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(header_bar_informations_grid, header_bar_informations_settings_label, 3, 0, 1, 1);
GtkWidget *header_bar_informations_settings_value = create_combo_box();
add_to_combo_box(header_bar_informations_settings_value, "TRUE");
add_to_combo_box(header_bar_informations_settings_value, "FALSE");
add_to_grid(header_bar_informations_grid, header_bar_informations_settings_value, 3, 1, 1, 1);
GtkWidget *header_bar_informations_add_button = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(header_bar_informations_grid, header_bar_informations_add_button, 4, 0, 2, 1);
add_to_box(header_bar_informations_main_box, header_bar_informations_grid, START, TRUE, FALSE, 0, 14, 0, 21, 21);
add_to_frame(header_bar_informations_main_box_frame, header_bar_informations_main_box, 0, 18, 0, 0);
add_to_box(Header_bar_case, header_bar_informations_main_box_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(Windows_box, Header_bar_case, START, TRUE, TRUE, 0, 25, 0, 0, 0);
GtkWidget *scrolled_window_case = create_box(GTK_ORIENTATION_VERTICAL, GTK_ALIGN_START, 0);
GtkWidget *scrolled_window_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *scrolled_window_label = create_label("scrolled window", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(scrolled_window_label_frame, scrolled_window_label, 5, 5, 0, 0);
add_to_box(scrolled_window_case, scrolled_window_label_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
GtkWidget *scrolled_window_informations_main_box_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *scrolled_window_informations_main_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *scrolled_window_informations_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *scrolled_window_informations_horizontal_label = create_label("Horizontal", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(scrolled_window_informations_grid, scrolled_window_informations_horizontal_label, 0, 0, 1, 1);
GtkWidget *scrolled_window_informations_horizontal_value = create_combo_box();
add_to_combo_box(scrolled_window_informations_horizontal_value, "TRUE");
add_to_combo_box(scrolled_window_informations_horizontal_value, "FALSE");
add_to_grid(scrolled_window_informations_grid, scrolled_window_informations_horizontal_value, 0, 1, 1, 1);
GtkWidget *scrolled_window_informations_vertical_label = create_label("Vertical", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(scrolled_window_informations_grid, scrolled_window_informations_vertical_label, 1, 0, 1, 1);
GtkWidget *scrolled_window_informations_vertical_value = create_combo_box();
add_to_combo_box(scrolled_window_informations_vertical_value, "TRUE");
add_to_combo_box(scrolled_window_informations_vertical_value, "FALSE");
add_to_grid(scrolled_window_informations_grid, scrolled_window_informations_vertical_value, 1, 1, 1, 1);
GtkWidget *scrolled_window_informations_add_button = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(scrolled_window_informations_grid, scrolled_window_informations_add_button, 2, 0, 2, 1);
add_to_box(scrolled_window_informations_main_box, scrolled_window_informations_grid, START, TRUE, FALSE, 0, 14, 0, 0, 0);
add_to_frame(scrolled_window_informations_main_box_frame, scrolled_window_informations_main_box, 0, 18, 21, 0);
add_to_box(scrolled_window_case, scrolled_window_informations_main_box_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(Windows_box, scrolled_window_case, START, TRUE, TRUE, 0, 25, 0, 0, 0);
add_to_scrolled_window(scrolled_window_window, Windows_box);
add_to_stack(stack_catalog, scrolled_window_window, "Windows");
GtkWidget *scrolled_containers_window = create_scrolled_window(FALSE, TRUE);
GtkWidget *Containers_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 7);
GtkWidget *Box_case = create_box(GTK_ORIENTATION_VERTICAL, GTK_ALIGN_START, 0);
GtkWidget *Box_case_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Box_case_label = create_label("Box", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Box_case_label_frame, Box_case_label, 5, 5, 0, 0);
add_to_box(Box_case, Box_case_label_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
GtkWidget *Box_case_informations_main_box_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Box_case_informations_main_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Box_case_informations_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *Box_case_informations_orientation_label = create_label("Orientation", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Box_case_informations_grid, Box_case_informations_orientation_label, 0, 0, 1, 1);
GtkWidget *Box_case_informations_orientation_value = create_combo_box();
add_to_combo_box(Box_case_informations_orientation_value, "GTK_ORIENTATION_HORIZONTAL");
add_to_combo_box(Box_case_informations_orientation_value, "GTK_ORIENTATION_VERTICAL");
add_to_grid(Box_case_informations_grid, Box_case_informations_orientation_value, 0, 1, 1, 1);
GtkWidget *Box_case_informations_align_label = create_label("Align", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Box_case_informations_grid, Box_case_informations_align_label, 1, 0, 1, 1);
GtkWidget *Box_case_informations_align_value = create_combo_box();
add_to_combo_box(Box_case_informations_align_value, "GTK_ALIGN_START");
add_to_combo_box(Box_case_informations_align_value, "GTK_ALIGN_END");
add_to_combo_box(Box_case_informations_align_value, "GTK_ALIGN_CENTER");
add_to_combo_box(Box_case_informations_align_value, "-1");
add_to_grid(Box_case_informations_grid, Box_case_informations_align_value, 1, 1, 1, 1);
GtkWidget *Box_case_informations_spacing_label = create_label("Spacing", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Box_case_informations_grid, Box_case_informations_spacing_label, 2, 0, 1, 1);
GtkWidget *Box_case_informations_spacing_value = create_spin_button(0, 100, 5, 0, 0, FALSE, FALSE);
add_to_grid(Box_case_informations_grid, Box_case_informations_spacing_value, 2, 1, 1, 1);
GtkWidget *Box_case_informations_add = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Box_case_informations_grid, Box_case_informations_add, 3, 0, 2, 1);
add_to_box(Box_case_informations_main_box, Box_case_informations_grid, START, TRUE, FALSE, 0, 14, 0, 0, 0);
add_to_frame(Box_case_informations_main_box_frame, Box_case_informations_main_box, 5, 18, 18, 0);
add_to_box(Box_case, Box_case_informations_main_box_frame, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Box_case, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Fixed_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Fixed_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Fixed_label = create_label("Fixed", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Fixed_label_frame, Fixed_label, 5, 5, 0, 0);
add_to_box(Fixed_box, Fixed_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Fixed_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Fixed_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *Fixed_add = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Fixed_grid, Fixed_add, 0, 0, 2, 1);
add_to_frame(Fixed_grid_frame, Fixed_grid, 14, 14, 14, 0);
add_to_box(Fixed_box, Fixed_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Fixed_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Frame_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Frame_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Frame_label = create_label("Frame", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Frame_label_frame, Frame_label, 5, 5, 0, 0);
add_to_box(Frame_box, Frame_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Frame_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Frame_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *Frame_title_label = create_label("Title", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Frame_grid, Frame_title_label, 0, 0, 1, 1);
GtkWidget *Frame_title_value = create_entry(NULL, NULL, TRUE, TRUE, 20, 0.5);
add_to_grid(Frame_grid, Frame_title_value, 0, 1, 1, 1);
GtkWidget *Frame_horizontal_placement_label = create_label("Horizontal placement", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Frame_grid, Frame_horizontal_placement_label, 1, 0, 1, 1);
GtkWidget *Frame_horizontal_placement_value = create_spin_button(0, 1, 0.5, 0.5, 1, FALSE, TRUE);
add_to_grid(Frame_grid, Frame_horizontal_placement_value, 1, 1, 1, 1);
GtkWidget *Frame_vertical_placement_label = create_label("Vertical placement", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Frame_grid, Frame_vertical_placement_label, 2, 0, 1, 1);
GtkWidget *Frame_vertical_placement_value = create_spin_button(0, 1, 0.5, 0.5, 1, FALSE, TRUE);
add_to_grid(Frame_grid, Frame_vertical_placement_value, 2, 1, 1, 1);
GtkWidget *Frame_add = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Frame_grid, Frame_add, 3, 0, 2, 1);
add_to_frame(Frame_grid_frame, Frame_grid, 14, 14, 14, 0);
add_to_box(Frame_box, Frame_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Frame_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Grid_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Grid_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Grid_label = create_label("Grid", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Grid_label_frame, Grid_label, 5, 5, 0, 0);
add_to_box(Grid_box, Grid_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Grid_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Grid_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *Grid_rows_spacing_label = create_label("Rows spacing", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Grid_grid, Grid_rows_spacing_label, 0, 0, 1, 1);
GtkWidget *Grid_rows_spacing_value = create_spin_button(0, 100, 5, 0, 0, FALSE, TRUE);
add_to_grid(Grid_grid, Grid_rows_spacing_value, 0, 1, 1, 1);
GtkWidget *Grid_columns_spacing_label = create_label("Columns spacing", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Grid_grid, Grid_columns_spacing_label, 1, 0, 1, 1);
GtkWidget *Grid_columns_spacing_value = create_spin_button(0, 100, 5, 0, 0, FALSE, TRUE);
add_to_grid(Grid_grid, Grid_columns_spacing_value, 1, 1, 1, 1);
GtkWidget *Grid_rows_homogeneous_label = create_label("Rows homogeneous", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Grid_grid, Grid_rows_homogeneous_label, 2, 0, 1, 1);
GtkWidget *Grid_rows_homogeneous_value = create_combo_box();
add_to_combo_box(Grid_rows_homogeneous_value, "TRUE");
add_to_combo_box(Grid_rows_homogeneous_value, "FALSE");
add_to_grid(Grid_grid, Grid_rows_homogeneous_value, 2, 1, 1, 1);
GtkWidget *Grid_columns_homogeneous_label = create_label("Columns homogeneous", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Grid_grid, Grid_columns_homogeneous_label, 3, 0, 1, 1);
GtkWidget *Grid_columns_homogeneous_value = create_combo_box();
add_to_combo_box(Grid_columns_homogeneous_value, "TRUE");
add_to_combo_box(Grid_columns_homogeneous_value, "FALSE");
add_to_grid(Grid_grid, Grid_columns_homogeneous_value, 3, 1, 1, 1);
GtkWidget *Grid_add = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Grid_grid, Grid_add, 4, 0, 2, 1);
add_to_frame(Grid_grid_frame, Grid_grid, 14, 14, 14, 0);
add_to_box(Grid_box, Grid_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Grid_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Paned_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Paned_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Paned_label = create_label("Paned", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Paned_label_frame, Paned_label, 7, 7, 14, 0);
add_to_box(Paned_box, Paned_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Paned_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Paned_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *Paned_orientation_label = create_label("Orientation", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Paned_grid, Paned_orientation_label, 0, 0, 1, 1);
GtkWidget *Paned_orientation_value = create_combo_box();
add_to_combo_box(Paned_orientation_value, "GTK_ORIENTATION_HORIZONTAL");
add_to_combo_box(Paned_orientation_value, "GTK_ORIENTATION_VERTICAL");
add_to_grid(Paned_grid, Paned_orientation_value, 0, 1, 1, 1);
GtkWidget *Paned_default_position_label = create_label("Default position", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Paned_grid, Paned_default_position_label, 1, 0, 1, 1);
GtkWidget *Paned_default_position_value = create_spin_button(0, 1000, 100, 500, 0, FALSE, TRUE);
add_to_grid(Paned_grid, Paned_default_position_value, 1, 1, 1, 1);
GtkWidget *Paned_show_handle_label = create_label("Show Handle", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Paned_grid, Paned_show_handle_label, 2, 0, 1, 1);
GtkWidget *Paned_show_handle_combo_box = create_combo_box();
add_to_combo_box(Paned_show_handle_combo_box, "TRUE");
add_to_combo_box(Paned_show_handle_combo_box, "FALSE");
add_to_grid(Paned_grid, Paned_show_handle_combo_box, 2, 1, 1, 1);
GtkWidget *Paned_add = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Paned_grid, Paned_add, 3, 0, 2, 1);
add_to_frame(Paned_grid_frame, Paned_grid, 14, 14, 14, 0);
add_to_box(Paned_box, Paned_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Paned_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Stack_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 0);
GtkWidget *Stack_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Stack_label = create_label("Stack", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Stack_label_frame, Stack_label, 7, 7, 14, 0);
add_to_box(Stack_box, Stack_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Stack_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Stack_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *stack_switcher_widget_label = create_label("Switcher ID", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Stack_grid, stack_switcher_widget_label, 0, 0, 1, 1);
GtkWidget *stack_switcher_widget_entry = create_entry(NULL, "The switcher ID", TRUE, TRUE, 20, 0.5);
add_to_grid(Stack_grid, stack_switcher_widget_entry, 0, 1, 1, 1);
GtkWidget *stack_transition_type_label = create_label("Transition Type", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Stack_grid, stack_transition_type_label, 1, 0, 1, 1);
GtkWidget *stack_transition_type_value_combo_box = create_combo_box();
add_to_combo_box(stack_transition_type_value_combo_box, "GTK_STACK_TRANSITION_TYPE_CROSSFADE");
add_to_combo_box(stack_transition_type_value_combo_box, "GTK_STACK_TRANSITION_TYPE_NONE");
add_to_combo_box(stack_transition_type_value_combo_box, "GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT");
add_to_combo_box(stack_transition_type_value_combo_box, "GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT");
add_to_grid(Stack_grid, stack_transition_type_value_combo_box, 1, 1, 1, 1);
GtkWidget *stack_duration_label = create_label("Duration", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Stack_grid, stack_duration_label, 2, 0, 1, 1);
GtkWidget *stack_duration_value_spin_button = create_spin_button(0, 1000, 100, 500, 0, FALSE, TRUE);
add_to_grid(Stack_grid, stack_duration_value_spin_button, 2, 1, 1, 1);
GtkWidget *stack_informations_add_button = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Stack_grid, stack_informations_add_button, 3, 0, 2, 1);
add_to_frame(Stack_grid_frame, Stack_grid, 14, 14, 14, 0);
add_to_box(Stack_box, Stack_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Stack_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
GtkWidget *Switcher_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 10);
GtkWidget *Switcher_label_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Switcher_label = create_label("Switcher", 14, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_frame(Switcher_label_frame, Switcher_label, 7, 7, 14, 0);
add_to_box(Switcher_box, Switcher_label_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
GtkWidget *Switcher_grid_frame = create_frame(NULL, 0.5, 0.5);
GtkWidget *Switcher_grid = create_grid(7, 7, TRUE, FALSE);
GtkWidget *switcher_spacing_label = create_label("Spacing", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Switcher_grid, switcher_spacing_label, 0, 0, 1, 1);
GtkWidget *switcher_spacing_value_spin_button = create_spin_button(0, 100, 5, 5, 0, FALSE, TRUE);
add_to_grid(Switcher_grid, switcher_spacing_value_spin_button, 0, 1, 1, 1);
GtkWidget *same_size_label = create_label("Same Size", 12, "Arial", "#000000", "#f6f5f4", GTK_JUSTIFY_LEFT, FALSE, 0, 0, TRUE);
add_to_grid(Switcher_grid, same_size_label, 1, 0, 1, 1);
GtkWidget *same_size_value_combo_box = create_combo_box();
add_to_combo_box(same_size_value_combo_box, "TRUE");
add_to_combo_box(same_size_value_combo_box, "FALSE");
add_to_grid(Switcher_grid, same_size_value_combo_box, 1, 1, 1, 1);
GtkWidget *switcher_informations_add_button = create_button(GTK_RELIEF_NORMAL, "                                                        Add                                                 ", FALSE, NULL, NULL, NULL);
add_to_grid(Switcher_grid, switcher_informations_add_button, 2, 0, 2, 1);
add_to_frame(Switcher_grid_frame, Switcher_grid, 14, 14, 14, 0);
add_to_box(Switcher_box, Switcher_grid_frame, START, FALSE, FALSE, 0, 0, 0, 0, 0);
add_to_box(Containers_box, Switcher_box, START, TRUE, TRUE, 0, 14, 0, 0, 0);
add_to_scrolled_window(scrolled_containers_window, Containers_box);
add_to_stack(stack_catalog, scrolled_containers_window, "Containers");
GtkWidget *scrolled_widgets_window = create_scrolled_window(FALSE, TRUE);
GtkWidget *Widgets_box = create_box(GTK_ORIENTATION_VERTICAL, -1, 7);
GtkWidget *Widgets = create_button(GTK_RELIEF_NORMAL, "Widgets", FALSE, NULL, NULL, NULL);
add_to_box(Widgets_box, Widgets, START, TRUE, TRUE, 0, 7, 0, 0, 0);
GtkWidget *Widgets2 = create_button(GTK_RELIEF_NORMAL, "Widgets", FALSE, NULL, NULL, NULL);
add_to_box(Widgets_box, Widgets2, START, TRUE, TRUE, 0, 0, 0, 0, 0);
GtkWidget *Widgets3 = create_button(GTK_RELIEF_NORMAL, "Widgets", FALSE, NULL, NULL, NULL);
add_to_box(Widgets_box, Widgets3, START, TRUE, TRUE, 0, 0, 0, 0, 0);
GtkWidget *Widgets4 = create_button(GTK_RELIEF_NORMAL, "Widgets", FALSE, NULL, NULL, NULL);
add_to_box(Widgets_box, Widgets4, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_scrolled_window(scrolled_widgets_window, Widgets_box);
add_to_stack(stack_catalog, scrolled_widgets_window, "Widgets");
add_to_box(widgets_catalog_box, stack_catalog, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(second_space_box, widgets_catalog_box, START, TRUE, TRUE, 0, 7, 0, 7, 0);
add_to_paned(build_space_paned, second_space_box, SECOND);
add_to_paned(main_paned, build_space_paned, SECOND);
add_to_box(app_box, main_paned, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(main_box, app_box, START, TRUE, TRUE, 0, 7, 0, 7, 7);
GtkWidget *control_box = create_box(GTK_ORIENTATION_HORIZONTAL, -1, 0);
GtkWidget *generate_button = create_button(GTK_RELIEF_NORMAL, "Generate", FALSE, NULL, NULL, NULL);
add_to_box(control_box, generate_button, START, FALSE, FALSE, 0, 0, 0, 0, 7);
GtkWidget *drag_button = create_button(GTK_RELIEF_NORMAL, "Drag", FALSE, NULL, NULL, NULL);
add_to_box(control_box, drag_button, START, TRUE, TRUE, 0, 0, 0, 0, 0);
add_to_box(main_box, control_box, START, FALSE, FALSE, 0, 7, 7, 7, 7);
add_to_container(window, main_box);
show_widget(window);
}
int main(int argc, char *argv[]){
    GtkApplication *app = gtk_application_new("org.example.app", G_APPLICATION_DEFAULT_FLAGS);
    g_signal_connect(app, "activate", G_CALLBACK(activate), NULL);
    int status = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return status;
}
